# -*- coding: utf-8 -*-
"""Capstone.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JFp5-d-oy2ejN2A9fCLgg30GLOsyE-DW
"""

from google.colab import files
uploaded = files.upload()

import zipfile
import os

zip_path = '/content/img.zip'  # change this to match the uploaded filename
with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall('/content/images')  # extract to folder

!unzip -o /content/img.zip -d /content/images

image_folder = '/content/images/img'
images = [f for f in os.listdir(image_folder) if f.lower().endswith('.png')]
print(f"Total images: {len(images)}")

import os
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers, models, Input, Model
from sklearn.model_selection import train_test_split
import xgboost as xgb
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score
import cv2
import glob

# Load CSV files
df_train = pd.read_csv('/content/lits_train.csv')
df_test = pd.read_csv('/content/lits_test.csv')

# Folder where images are stored
image_folder = '/content/images/img'
dataset_paths = sorted(glob.glob(os.path.join(image_folder, '*.png')))

# Define the load_images function
def load_images(image_paths):
    images = []
    for path in image_paths:
        img = cv2.imread(path, cv2.IMREAD_GRAYSCALE)
        if img.shape != (128, 128):
            img = cv2.resize(img, (128, 128))
        images.append(img)
    return np.array(images).reshape(-1, 128, 128, 1)

# Load dataset
X = load_images(dataset_paths)
X = X / 255.0

# Extract labels
y = df_train['tumor_mask_empty'].values[:len(X)]

# Split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# CNN model
inputs = Input(shape=(128, 128, 1))
x = layers.Conv2D(64, (3, 3), activation='relu')(inputs)
x = layers.MaxPooling2D((2, 2))(x)
x = layers.Conv2D(128, (3, 3), activation='relu')(x)
x = layers.MaxPooling2D((2, 2))(x)
x = layers.Flatten()(x)
x = layers.Dense(256, activation='relu')(x)
outputs = layers.Dense(1, activation='sigmoid')(x)

cnn_model = Model(inputs=inputs, outputs=outputs)
cnn_model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

# Train CNN
history = cnn_model.fit(X_train, y_train, epochs=10, batch_size=4, validation_split=0.2)
# Extract CNN features
feature_extractor = Model(inputs=cnn_model.input, outputs=cnn_model.layers[-2].output)
X_train_features = feature_extractor.predict(X_train)
X_test_features = feature_extractor.predict(X_test)

# XGBoost on CNN features
xgb_model = XGBClassifier(n_estimators=100, learning_rate=0.1, max_depth=3)
xgb_model.fit(X_train_features, y_train.ravel())
y_pred = xgb_model.predict(X_test_features)
accuracy = accuracy_score(y_test, y_pred)
print(f'XGBoost Accuracy: {accuracy:.4f}')

feature_extractor.save('/content/feature_extractor_model.h5')

feature_extractor = tf.keras.models.load_model('/content/feature_extractor_model.h5')

# Save your trained models (you should have already done this)
feature_extractor.save('/content/feature_extractor_model.h5')

import joblib
joblib.dump(xgb_model, '/content/xgb_model.pkl')

!pip install streamlit pyngrok xgboost opencv-python

import os
os.environ["NGROK_AUTHTOKEN"] = "2jobd681TGhlxwJLHtUfB2JfBrp_7BBJHimf3bV2aJyti3B5K"

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import numpy as np
# import pandas as pd
# import cv2
# import glob
# import os
# from tensorflow.keras.models import load_model, Model
# from tensorflow.keras import layers, Input
# from xgboost import XGBClassifier
# import joblib
# 
# # Load trained models (you must save them after training in Colab)
# cnn_model = load_model('/content/feature_extractor_model.h5')
# xgb_model = joblib.load('/content/xgb_model.pkl')
# 
# # Feature extractor
# feature_extractor = Model(inputs=cnn_model.input, outputs=cnn_model.layers[-2].output)
# 
# def load_image(image_file):
#     img = cv2.imdecode(np.frombuffer(image_file.read(), np.uint8), cv2.IMREAD_GRAYSCALE)
#     img = cv2.resize(img, (128, 128))
#     return img.reshape(1, 128, 128, 1) / 255.0
# 
# st.title("Tumor Detection using CNN + XGBoost")
# 
# uploaded_file = st.file_uploader("Upload an image", type=['png', 'jpg', 'jpeg'])
# if uploaded_file is not None:
#     st.image(uploaded_file, caption='Uploaded Image', width=250)
#     img = load_image(uploaded_file)
# 
#     cnn_features = feature_extractor.predict(img)
#     prediction = xgb_model.predict(cnn_features)[0]
#     st.write("Prediction:", "Tumor Detected" if prediction == 1 else "No Tumor")

!streamlit run app.py &

import streamlit as st
import numpy as np
import cv2
import tensorflow as tf
import pickle

# Load models
cnn_model = tf.keras.models.load_model('/content/feature_extractor_model.h5')  # Make sure this file exists
with open("/content/xgb_model.pkl", "rb") as f:
    xgb_model = pickle.load(f)  # XGBoost model on CNN features

st.title("Liver Tumor Detection from CT Scan")

uploaded_file = st.file_uploader("Upload a Liver CT Scan Image", type=["png", "jpg", "jpeg"])

if uploaded_file is not None:
    # Display image
    file_bytes = np.asarray(bytearray(uploaded_file.read()), dtype=np.uint8)
    img = cv2.imdecode(file_bytes, cv2.IMREAD_GRAYSCALE)

    # Preprocess
    img_resized = cv2.resize(img, (128, 128))
    img_input = img_resized.reshape(1, 128, 128, 1) / 255.0

    st.image(img, caption="Uploaded CT Scan", use_container_width=True)

    # Feature extraction from CNN
    feature_extractor = tf.keras.Model(inputs=cnn_model.input, outputs=cnn_model.layers[-2].output)
    cnn_features = feature_extractor.predict(img_input)

    # XGBoost Prediction
    prediction = xgb_model.predict(cnn_features)[0]
    label = "Tumor Detected" if prediction == 1 else "No Tumor Found"

    # Display result
    st.success(f"Prediction: {label}")

!pip install streamlit pyngrok pillow

!ngrok config add-authtoken 2w5cMSLJWZtB20oKypL38j8uJgj_7Ets2As4UPW5udBCnKJoY

# Install required packages
!pip install streamlit pyngrok pillow

# Write the Streamlit app to a file
code = """
import streamlit as st
from PIL import Image
import numpy as np

def predict_tumor(image_array):
    return "Tumor Detected" if np.mean(image_array) < 100 else "No Tumor Detected"

st.title("Liver Cancer Detection from CT Scans")
st.write("Upload a CT scan image to detect presence of liver tumor.")

uploaded_file = st.file_uploader("Choose a CT scan image", type=["jpg", "jpeg", "png"])

if uploaded_file is not None:
    image = Image.open(uploaded_file).convert('L')  # grayscale
    st.image(image, caption="Uploaded CT Image", use_container_width=True)

    image_resized = image.resize((224, 224))
    image_array = np.array(image_resized)

    prediction = predict_tumor(image_array)
    st.subheader("Prediction:")
    st.success(prediction)
    """
with open("app.py", "w") as f:
    f.write(code)

# Start ngrok
from pyngrok import ngrok
ngrok.kill()
public_url = ngrok.connect(8501)
print(f"Public URL: {public_url}")

# Run Streamlit app
!streamlit run app.py --server.enableCORS false --server.enableXsrfProtection false &